version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    steps:
      - checkout
      - run:
          command: mvn compile
  spotless:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    steps:
      - checkout
      - run:
          command: mvn spotless:check
  test:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    steps:
      - checkout
      - run:
          command: mvn test
workflows:
  version: 2
  build_check_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - spotless:
          requires:
            - build